Production-ready content for MSAL Go
MicrosoftDocs/microsoft-authentication-library-for-go pull request #1
Opened 2023-03-29 20:14 UTC by localden

2023-04-12 22:35 UTC, pmaytak commented on msal-go/index.md
> +> icrosoft Authentication Library (MSAL) for Go is a new addition to the MSAL family of libraries. It has been made available in production-ready preview to gauge customer interest and to gather feed
```suggestion
> Microsoft Authentication Library (MSAL) for Go is a new addition to the MSAL family of libraries. It has been made available in production-ready preview to gauge customer interest and to gather feedback from the community. We welcome all contributors (see [contribution guidelines in the library repository](https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/CONTRIBUTING.md)) to help us improve the library.**
```

2023-04-12 23:22 UTC, rayluo commented on msal-go/index.md
> +    result, err := publicClientApp.AcquireToken"ByOneofTheActualMethods"([]string{"your_scope"}, ...(other parameters depending on the function))
Many of the wording from this document sound very familiar to me. :-)

Half joking aside, this particular line is not currently syntactically valid. Was that intentional? Do you consider write it like below?
```suggestion
    result, err := publicClientApp.AcquireTokenByOneofTheActualMethods([]string{"your_scope"}, ...(other parameters depending on the function))
```

2023-04-14 16:17 UTC, bgavrilMS commented on msal-go/design.md
> +The public API will be encapsulated in `apps/`.  `apps/` has 3 packages of interest to users:
```suggestion
The public API is encapsulated in `apps/`.  `apps/` has 3 packages of interest to users:
```

2023-04-14 16:18 UTC, bgavrilMS commented on msal-go/design.md
> +- `public/` - This is what MSAL calls the Public Application Client (service client)
```suggestion
- `public/` - Covers the Public Application Client. These are apps that run on the user's computer, such as command line interface apps. 
```

2023-04-14 16:19 UTC, bgavrilMS commented on msal-go/design.md
> +- `confidential/` - This is what MSAL calls the Confidential Application Client (service)
```suggestion
- `confidential/` - Covers the Confidential Application Client. These are apps that run on servers - web apps, web APIs which get tokens for users and web APIs which get tokens on behalf of themselves (service to service communication)

2023-04-14 16:20 UTC, bgavrilMS commented on msal-go/design.md
> +JSON must be handled specially in our app. The basics are, if we receive fields that our structs do not contain, we cannot drop them.  We must send them back to the service.
```suggestion
JSON must be handled specially in our app. The basics are, if we receive fields that our structs do not contain, we cannot drop them, to ensure backwards and future compatibility.
```

2023-04-14 16:21 UTC, bgavrilMS commented on msal-go/design.md
> +### TBD: Confidential applications needs to handle multiple users without one big cache
```suggestion
### Confidential applications needs to handle multiple users without one big cache
```

2023-04-14 17:07 UTC, bgavrilMS commented on msal-go/index.md
> +We use [Stack Overflow](https://stackoverflow.com/questions/tagged/azure-ad-msal) to work with the community on supporting Azure Active Directory and its SDKs, including this one! We highly recommend
Do we really monitor Stack Overflow?

2023-04-14 17:07 UTC, bgavrilMS approved these changes

2023-04-14 17:40 UTC, rayluo commented on msal-go/index.md
> +We use [Stack Overflow](https://stackoverflow.com/questions/tagged/azure-ad-msal) to work with the community on supporting Azure Active Directory and its SDKs, including this one! We highly recommend
I believe there are some support engineers from Microsoft monitoring StackOverflow. Not sure how often. MSAL team here historically does not monitor StackOverflow. That being said, occasionally when I receive 1:1 questions on Teams, and if the question is generic, I suggest the question asker to post their question on StackOverflow, and paste me the link if it got unanswered after a day or two.

TL;DR. I would still suggest keep this StackOverflow paragraph.

2023-04-14 19:15 UTC, localden commented on msal-go/index.md
> +We use [Stack Overflow](https://stackoverflow.com/questions/tagged/azure-ad-msal) to work with the community on supporting Azure Active Directory and its SDKs, including this one! We highly recommend
I am monitoring Stack Overflow @bgavrilMS @rayluo 😄

2023-04-21 12:14 UTC, Dickson-Mwendia requested changes
@localden a few minor suggestions here. In line with docs' contributor guide all H1, H2s/H3s should be sentence case.  Otherwise, it looks good. I'll make a few content updates once this is merged. Thanks!

2023-04-21 12:14 UTC, Dickson-Mwendia commented on msal-go/index.md
> +1. If there is no suitable token in the cache, or you choose to skip this step, now we can send a request to AAD to obtain a token.
If there's no suitable token in the cache, or you choose to skip this step, send a request to Azure AD to obtain a token. There are different methods to acquire a token based on your application type and scenario. Here, we demonstrate a placeholder flow.

2023-04-21 12:14 UTC, Dickson-Mwendia commented on msal-go/index.md
> +You can view the [dev apps](https://github.com/AzureAD/microsoft-authentication-library-for-go/tree/dev/apps/tests/devapps) on how to use MSAL Go with various application types in various scenarios.
You can view the [developer sample apps](https://github.com/AzureAD/microsoft-authentication-library-for-go/tree/dev/apps/tests/devapps) on how to use MSAL Go with various application types in different scenarios.

2023-04-21 12:14 UTC, Dickson-Mwendia commented on msal-go/index.md
> +You can view the [dev apps](https://github.com/AzureAD/microsoft-authentication-library-for-go/tree/dev/apps/tests/devapps) on how to use MSAL Go with various application types in various scenarios.
I'd recommend doing away with this pointer to the wiki

2023-04-21 12:14 UTC, Dickson-Mwendia commented on msal-go/index.md
> +This library controls how users sign-in and access services. We recommend you always take the latest version of our library in your app when possible. We use [semantic versioning](http://semver.org)
This library controls how users sign-in and access services. We recommend using the latest version of our library in your app when possible. We use [semantic versioning](http://semver.org) so you can control the risk associated with updating your app. As an example, always downloading the latest minor version number (e.g. x.*y*.x) ensures you get the latest security and feature enhancements but our API surface remains the same. You can always see the latest version and release notes under the Releases tab of GitHub.

2023-04-21 12:14 UTC, Dickson-Mwendia commented on msal-go/TOC.yml
> +- name: Design Guide
- name: Design guide

2023-04-21 12:14 UTC, Dickson-Mwendia commented on msal-go/TOC.yml
> +- name: Error Design
- name: Error design

2023-04-21 12:14 UTC, Dickson-Mwendia commented on msal-go/design.md
> +## General Structure
## General structure

2023-04-21 12:14 UTC, Dickson-Mwendia commented on msal-go/design.md
> +Public Surface
Public surface

2023-04-21 12:14 UTC, Dickson-Mwendia commented on msal-go/design.md
> +### JSON Handling
### JSON handling

2023-04-21 12:14 UTC, Dickson-Mwendia commented on msal-go/design.md
> +## Adding A Feature
## Adding a feature

2023-04-21 12:14 UTC, Dickson-Mwendia commented on msal-go/design.md
> +## Notable Differences To Other Clients
## Notable differences to other clients

2023-04-21 12:14 UTC, Dickson-Mwendia commented on msal-go/design.md
> +In this section we will be talking about `internal/`.
In this section, we will be talking about `internal/`.

2023-04-21 12:14 UTC, Dickson-Mwendia commented on msal-go/design.md
> +### Confidential applications needs to handle multiple users without one big cache
### Confidential applications need to handle multiple users without one big cache

2023-04-21 12:14 UTC, Dickson-Mwendia commented on msal-go/error-design.md
> +## Implementing Service Side Errors
## Implementing service-side errors

2023-04-21 12:14 UTC, Dickson-Mwendia commented on msal-go/error-design.md
> +## Future Decisions
## Future decisions

2023-04-21 12:14 UTC, Dickson-Mwendia commented on msal-go/error-design.md
> +### MSAL error goals
Thoughts on placing these points at the top of the article, - just below the sentence in ##background?

2023-04-22 01:01 UTC, merged